OUTPUT_DIR = "outputs"
GENERAL_HTML_PATH = "outputs/generated.html"
#layout_detection
#edge
EDGE_THRESHOLD_1 = 50
EDGE_THRESHOLD_2 = 150
#contur filter
MIN_CONTOUR_AREA = 800
MAX_CONTOUR_AREA = 200000
#shape 
BUTTON_ASPECT_RATIO_MIN = 2.0
INPUT_ASPECT_RATIO_MIN = 4.0
CONTAINER_AREA_THRESHOLD = 50000
#OCR 
OCR_CONFIDENCE_THRESHOLD = 60
OCR_MERGE_X_THRESHOLD = 15
OCR_MERGE_Y_THRESHOLD = 10
#hierarchy_builder
ROW_ALIGNMENT_THRESHOLD = 20
COLUMN_ALIGNMENT_THRESHOLD = 20
MIN_GROUP_SIZE = 2

#style
KMEANS_CLUSTERS = 2
FONT_SIZE_SCALE = 0.6

#LLM 
GEMINI_MODEL = "gemini-2.5-flash"